# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/oem/Downloads/CHESS

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/oem/Downloads/CHESS

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/oem/Downloads/CHESS/CMakeFiles /home/oem/Downloads/CHESS/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/oem/Downloads/CHESS/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CHESS

# Build rule for target.
CHESS: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CHESS
.PHONY : CHESS

# fast build rule for target.
CHESS/fast:
	$(MAKE) -f CMakeFiles/CHESS.dir/build.make CMakeFiles/CHESS.dir/build
.PHONY : CHESS/fast

src/Bishop.o: src/Bishop.cpp.o

.PHONY : src/Bishop.o

# target to build an object file
src/Bishop.cpp.o:
	$(MAKE) -f CMakeFiles/CHESS.dir/build.make CMakeFiles/CHESS.dir/src/Bishop.cpp.o
.PHONY : src/Bishop.cpp.o

src/Bishop.i: src/Bishop.cpp.i

.PHONY : src/Bishop.i

# target to preprocess a source file
src/Bishop.cpp.i:
	$(MAKE) -f CMakeFiles/CHESS.dir/build.make CMakeFiles/CHESS.dir/src/Bishop.cpp.i
.PHONY : src/Bishop.cpp.i

src/Bishop.s: src/Bishop.cpp.s

.PHONY : src/Bishop.s

# target to generate assembly for a file
src/Bishop.cpp.s:
	$(MAKE) -f CMakeFiles/CHESS.dir/build.make CMakeFiles/CHESS.dir/src/Bishop.cpp.s
.PHONY : src/Bishop.cpp.s

src/King.o: src/King.cpp.o

.PHONY : src/King.o

# target to build an object file
src/King.cpp.o:
	$(MAKE) -f CMakeFiles/CHESS.dir/build.make CMakeFiles/CHESS.dir/src/King.cpp.o
.PHONY : src/King.cpp.o

src/King.i: src/King.cpp.i

.PHONY : src/King.i

# target to preprocess a source file
src/King.cpp.i:
	$(MAKE) -f CMakeFiles/CHESS.dir/build.make CMakeFiles/CHESS.dir/src/King.cpp.i
.PHONY : src/King.cpp.i

src/King.s: src/King.cpp.s

.PHONY : src/King.s

# target to generate assembly for a file
src/King.cpp.s:
	$(MAKE) -f CMakeFiles/CHESS.dir/build.make CMakeFiles/CHESS.dir/src/King.cpp.s
.PHONY : src/King.cpp.s

src/Knight.o: src/Knight.cpp.o

.PHONY : src/Knight.o

# target to build an object file
src/Knight.cpp.o:
	$(MAKE) -f CMakeFiles/CHESS.dir/build.make CMakeFiles/CHESS.dir/src/Knight.cpp.o
.PHONY : src/Knight.cpp.o

src/Knight.i: src/Knight.cpp.i

.PHONY : src/Knight.i

# target to preprocess a source file
src/Knight.cpp.i:
	$(MAKE) -f CMakeFiles/CHESS.dir/build.make CMakeFiles/CHESS.dir/src/Knight.cpp.i
.PHONY : src/Knight.cpp.i

src/Knight.s: src/Knight.cpp.s

.PHONY : src/Knight.s

# target to generate assembly for a file
src/Knight.cpp.s:
	$(MAKE) -f CMakeFiles/CHESS.dir/build.make CMakeFiles/CHESS.dir/src/Knight.cpp.s
.PHONY : src/Knight.cpp.s

src/Pawn.o: src/Pawn.cpp.o

.PHONY : src/Pawn.o

# target to build an object file
src/Pawn.cpp.o:
	$(MAKE) -f CMakeFiles/CHESS.dir/build.make CMakeFiles/CHESS.dir/src/Pawn.cpp.o
.PHONY : src/Pawn.cpp.o

src/Pawn.i: src/Pawn.cpp.i

.PHONY : src/Pawn.i

# target to preprocess a source file
src/Pawn.cpp.i:
	$(MAKE) -f CMakeFiles/CHESS.dir/build.make CMakeFiles/CHESS.dir/src/Pawn.cpp.i
.PHONY : src/Pawn.cpp.i

src/Pawn.s: src/Pawn.cpp.s

.PHONY : src/Pawn.s

# target to generate assembly for a file
src/Pawn.cpp.s:
	$(MAKE) -f CMakeFiles/CHESS.dir/build.make CMakeFiles/CHESS.dir/src/Pawn.cpp.s
.PHONY : src/Pawn.cpp.s

src/Queen.o: src/Queen.cpp.o

.PHONY : src/Queen.o

# target to build an object file
src/Queen.cpp.o:
	$(MAKE) -f CMakeFiles/CHESS.dir/build.make CMakeFiles/CHESS.dir/src/Queen.cpp.o
.PHONY : src/Queen.cpp.o

src/Queen.i: src/Queen.cpp.i

.PHONY : src/Queen.i

# target to preprocess a source file
src/Queen.cpp.i:
	$(MAKE) -f CMakeFiles/CHESS.dir/build.make CMakeFiles/CHESS.dir/src/Queen.cpp.i
.PHONY : src/Queen.cpp.i

src/Queen.s: src/Queen.cpp.s

.PHONY : src/Queen.s

# target to generate assembly for a file
src/Queen.cpp.s:
	$(MAKE) -f CMakeFiles/CHESS.dir/build.make CMakeFiles/CHESS.dir/src/Queen.cpp.s
.PHONY : src/Queen.cpp.s

src/Rook.o: src/Rook.cpp.o

.PHONY : src/Rook.o

# target to build an object file
src/Rook.cpp.o:
	$(MAKE) -f CMakeFiles/CHESS.dir/build.make CMakeFiles/CHESS.dir/src/Rook.cpp.o
.PHONY : src/Rook.cpp.o

src/Rook.i: src/Rook.cpp.i

.PHONY : src/Rook.i

# target to preprocess a source file
src/Rook.cpp.i:
	$(MAKE) -f CMakeFiles/CHESS.dir/build.make CMakeFiles/CHESS.dir/src/Rook.cpp.i
.PHONY : src/Rook.cpp.i

src/Rook.s: src/Rook.cpp.s

.PHONY : src/Rook.s

# target to generate assembly for a file
src/Rook.cpp.s:
	$(MAKE) -f CMakeFiles/CHESS.dir/build.make CMakeFiles/CHESS.dir/src/Rook.cpp.s
.PHONY : src/Rook.cpp.s

src/board.o: src/board.cpp.o

.PHONY : src/board.o

# target to build an object file
src/board.cpp.o:
	$(MAKE) -f CMakeFiles/CHESS.dir/build.make CMakeFiles/CHESS.dir/src/board.cpp.o
.PHONY : src/board.cpp.o

src/board.i: src/board.cpp.i

.PHONY : src/board.i

# target to preprocess a source file
src/board.cpp.i:
	$(MAKE) -f CMakeFiles/CHESS.dir/build.make CMakeFiles/CHESS.dir/src/board.cpp.i
.PHONY : src/board.cpp.i

src/board.s: src/board.cpp.s

.PHONY : src/board.s

# target to generate assembly for a file
src/board.cpp.s:
	$(MAKE) -f CMakeFiles/CHESS.dir/build.make CMakeFiles/CHESS.dir/src/board.cpp.s
.PHONY : src/board.cpp.s

src/helper.o: src/helper.cpp.o

.PHONY : src/helper.o

# target to build an object file
src/helper.cpp.o:
	$(MAKE) -f CMakeFiles/CHESS.dir/build.make CMakeFiles/CHESS.dir/src/helper.cpp.o
.PHONY : src/helper.cpp.o

src/helper.i: src/helper.cpp.i

.PHONY : src/helper.i

# target to preprocess a source file
src/helper.cpp.i:
	$(MAKE) -f CMakeFiles/CHESS.dir/build.make CMakeFiles/CHESS.dir/src/helper.cpp.i
.PHONY : src/helper.cpp.i

src/helper.s: src/helper.cpp.s

.PHONY : src/helper.s

# target to generate assembly for a file
src/helper.cpp.s:
	$(MAKE) -f CMakeFiles/CHESS.dir/build.make CMakeFiles/CHESS.dir/src/helper.cpp.s
.PHONY : src/helper.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/CHESS.dir/build.make CMakeFiles/CHESS.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/CHESS.dir/build.make CMakeFiles/CHESS.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/CHESS.dir/build.make CMakeFiles/CHESS.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/pieces.o: src/pieces.cpp.o

.PHONY : src/pieces.o

# target to build an object file
src/pieces.cpp.o:
	$(MAKE) -f CMakeFiles/CHESS.dir/build.make CMakeFiles/CHESS.dir/src/pieces.cpp.o
.PHONY : src/pieces.cpp.o

src/pieces.i: src/pieces.cpp.i

.PHONY : src/pieces.i

# target to preprocess a source file
src/pieces.cpp.i:
	$(MAKE) -f CMakeFiles/CHESS.dir/build.make CMakeFiles/CHESS.dir/src/pieces.cpp.i
.PHONY : src/pieces.cpp.i

src/pieces.s: src/pieces.cpp.s

.PHONY : src/pieces.s

# target to generate assembly for a file
src/pieces.cpp.s:
	$(MAKE) -f CMakeFiles/CHESS.dir/build.make CMakeFiles/CHESS.dir/src/pieces.cpp.s
.PHONY : src/pieces.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... CHESS"
	@echo "... src/Bishop.o"
	@echo "... src/Bishop.i"
	@echo "... src/Bishop.s"
	@echo "... src/King.o"
	@echo "... src/King.i"
	@echo "... src/King.s"
	@echo "... src/Knight.o"
	@echo "... src/Knight.i"
	@echo "... src/Knight.s"
	@echo "... src/Pawn.o"
	@echo "... src/Pawn.i"
	@echo "... src/Pawn.s"
	@echo "... src/Queen.o"
	@echo "... src/Queen.i"
	@echo "... src/Queen.s"
	@echo "... src/Rook.o"
	@echo "... src/Rook.i"
	@echo "... src/Rook.s"
	@echo "... src/board.o"
	@echo "... src/board.i"
	@echo "... src/board.s"
	@echo "... src/helper.o"
	@echo "... src/helper.i"
	@echo "... src/helper.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/pieces.o"
	@echo "... src/pieces.i"
	@echo "... src/pieces.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

